title: Molly Prower's portfolio
description: >- # this means to ignore newlines until "baseurl:"
  I love cheese.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://molly.riceprower.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Some contact info
email: molls12@gmail.com
github_username: mollsprow

# https://jekyllrb.com/docs/collections/
collections:
  tabs:
    output: true
    # sort_by: order  # Doesn't appear to work in GH Pages; use `| sort` filter in the layout, instead

# Exclude certain files and directories from the build
# https://jekyllrb.com/docs/configuration/options/#global-configuration
exclude:
  - .github
  - .vscode
  - '*.gem'
  - '*.gemspec'
  - docs
  - Gemfile
  - gulpfile.js
  - js_tools
  - LICENSE
  - node_modules
  - package*.json
  - README.md
