# Based on: https://github.com/jakejarvis/cloudflare-purge-action

# Purges the Cloudflare CDN cache for this site, using a dedicated action.
# Triggers on the `page_build` event type:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#page_build

# Repo Secrets are used to inject the ZoneID and Cloudflare API Token.
# (token is restricted to only purging caches, and only on this site's domain)

name: "Purge Cloudflare Cache"
on:
  page_build:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0

        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_CACHE_TOKEN }}
